language: node_js

node_js: "6"

os:
  - linux
  - osx

git:
  depth: 1

addons:
  apt:
    packages:
    - fakeroot
    - dpkg
    - rpm
    - lintian
    - libdbus-1-dev
    - libglib2.0-dev
    - reprepro
    - createrepo

before_install:
- npm i -g npm@5.4.2

install:
- npm install
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run darwin; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run linux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run windows; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint linux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint shared; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run lint darwin; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd darwin; fi
- npm run test

before_cache:
- cd ..

cache:
  directories:
  - node_modules
  - darwin/node_modules
  - linux/node_modules
  - windows/node_modules

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && -n "$TRAVIS_TAG" ]]; then
    cd linux;
    openssl aes-256-cbc -K $encrypted_6866d25ad40b_key -iv $encrypted_6866d25ad40b_iv -in headset_priv.asc.enc -out headset_priv.asc -d;
    npm run repo;
    cd ..;
  fi

deploy:
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file:
    - linux/build/installers/*
    - darwin/build/installers/*.dmg
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: linux/gh-pages
  github_token: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
