language: node_js

node_js: "6"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
      - lintian
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_install:
  - npm i -g npm@5.4.2

install:
  - npm install
  - npm run linux
  - npm run darwin # needed for eslint to pass
  - npm run windows # needed for eslint to pass

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run lint
  - cd linux/
  - npm run test

git:
  depth: 1

cache:
  directories:
  - linux/node_modules
  - darwin/node_modules
  - windows/node_modules

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key: $GITHUB_TOKEN
    file: build/installers/*
    on:
      tags: true
