version: "{build}"

os: unstable

environment:
  nodejs_version: "6"
  CERT_PASSWORD:
    secure: pbjvH7kU0tV7o66vMiDgmA==

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g  npm@5.6.0
  - npm install
  - cd windows && npm install && cd..

before_build:
  - npm run lint windows

build_script:
  - cd windows
  - npm run build

test_script:
  - cd ..
  - npm run test:windows

cache:
  - node_modules
  - windows\node_modules
  - '%APPDATA%\npm-cache'

artifacts:
  - path: windows\build\installers\*.exe
    name: HeadsetApp

deploy:
  - provider: GitHub
    artifact: HeadsetApp
    auth_token: $(GITHUB_TOKEN)
    draft: true
    description: ''
    on:
      appveyor_repo_tag: true
